### ISSUE TITLE
Error Retrieving Media

### ISSUE THREAD

**Issue by MizterB** [tchellomello/python-arlo#103]
A couple days ago I noticed that HomeAssistant was no longer showing images from my Arlo cameras - the API was returning a 500 error.  Ultimately I found that the HA code could not retrieve any of the camera's last_video properties.

I decided to try connecting directly through the python-arlo API and see if I could get to the root cause.  I am seeing the following:
`from pyarlo import PyArlo
arlo = PyArlo("<user>", "<pass>")

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.7/site-packages/pyarlo/__init__.py", line 52, in __init__
    days=days)
  File "/usr/local/lib/python3.7/site-packages/pyarlo/media.py", line 29, in __init__
    self.videos = self.load(days)
  File "/usr/local/lib/python3.7/site-packages/pyarlo/media.py", line 69, in load
    )[0]
IndexError: list index out of range
`
It seems like Arlo may not longer be providing the expected data to initialize PyArlo, so I wanted to raise awareness and see if the root cause could be determined.

**Comment by MizterB** [comment]
I forgot that a recent addition to my system was an Arlo doorbell.  I tried removing that from the system config, and found that everything started working correctly again!  Any idea why a doorbell would be breaking the video code?

**Comment by tchellomello** [comment]
@MizterB thanks for reporting the issue. Doorbell is not yet supported and we might need to filter the object correctly as it could be mixing with the regular cameras.

**Comment by tchellomello** [comment]
@MizterB could you try to see if the code above workaround the problem?
