### ISSUE TITLE
Base Modes incorrect

### ISSUE THREAD

**Issue by sappsys** [tchellomello/python-arlo#107]
I'm running Python 2.7 and just did a fresh pip install of pyarlo
When I run it, I get incorrect modes returned :--

Devices : {'base_station': [<ArloBaseStation: Home>], 'cameras': [<ArloCamera: BackGardenCamera>, <ArloCamera: HallwayCamera>, <ArloCamera: GarageCamera>, <ArloCamera: KitchenCamera>, <ArloCamera: LivingRoomCamera>, <ArloCamera: LandingCamera>]}

Arlo Base Stations : [<ArloBaseStation: Home>]

Base : <ArloBaseStation: Home>

Base Mode : disarmed

Modes : [u'disarmed', 'schedule']

However the app and the website all report my correct list of modes which is :--
Armed,Disarmed,Schedule,Geofencing,andys,Night

Also, the "Night" mode is what is actually currently selected not "disarmed"

Code :--

[root@server pyarlo]# pip list | grep arlo
pyarlo (0.2.3)

from pyarlo import PyArlo
arlo  = PyArlo('xxx@xxx.com', '*********')

print
print("Devices : %s" % (arlo.devices))

print
print("Arlo Base Stations : %s" %(arlo.base_stations))

base = arlo.base_stations[0]

print
print("Base : %s" % (base))

print
print("Base Mode : %s" % (base.mode))

print
print("Modes : %s" % (base.available_modes))

print
print("Base Properties : %s" % (base.properties))

**Comment by brandontiller** [comment]
I had the same issue. I just deleted my custom modes in Arlo and recreated them. Working fine now. Pain though...

**Comment by sappsys** [comment]
Hi, I tried that and it worked. Strange as the app shows everything correct and the system worked, it was just this API interface that was showing the wrong info.
Thanks.
