### ISSUE TITLE
Trying to run..

### ISSUE THREAD

**Issue by danieledge** [tchellomello/python-arlo#13]
Hi,

I'm getting a syntax error when trying to execute the example. Any ideas what I'm doing wrong?

Thanks in advance! 

 File "newtest.py", line 7
    {'base_station': [ArloBaseStation: Home>]}
SyntaxError: invalid syntax

I'm getting the above error when trying to execute...

# connecting
from pyarlo import PyArlo
arlo  = PyArlo('myuser', 'bypass')

# listing devices
arlo.devices
{'base_station': [ArloBaseStation: Home>]}

**Comment by tchellomello** [comment]
Hello @danieledge , 

  Can you share your `newtest.py` file to see what is happening? 
  
   Are you getting a traceback? If so, can you share it too? 

 Thanks

**Comment by danieledge** [comment]
This was a problem with my python installation which I've now resolved. Thanks
