### ISSUE TITLE
Updating the Camera Snapshot

### ISSUE THREAD

**Issue by chaddotson** [tchellomello/python-arlo#19]
I'm wanting to script grabbing an image from each of my cameras.  Is there anyway to update each camera's current snapshot?

**Comment by chaddotson** [comment]
I figured out the endpoint and payload for taking a manual snapshot but unfortunately that does not update the "lastImage".

**Comment by tchellomello** [comment]
@chaddotson  did you try to run camera.update() to refresh the object? Could you share your script?

**Comment by tchellomello** [comment]
@chaddotson did it work for you?

**Comment by chaddotson** [comment]
Sorry got distracted  by something else.  I believe it worked to a point.  Seems I had trouble making sure it always worked.  I can't remember the details, will verify this week.

**Comment by chaddotson** [comment]
@tchellomello negatory.  

`
from logging import basicConfig, getLogger,  DEBUG, INFO
from pyarlo import PyArlo

logger = getLogger(__name__)

logging_config = dict(level=INFO, format='[%(asctime)s - %(filename)s:%(lineno)d - %(funcName)s - %(levelname)s] %(message)s')
basicConfig(**logging_config)

arlo = PyArlo(username, password)
for camera in arlo.cameras:
    camera.update()

    name = "{0}.jpg".format(camera.name)
    logger.info('Camera updated, saving \"%s\" to \"%s\"', camera.name, name)
    camera.last_video.download_thumbnail(name)
`

Does grab a thumbnail but does not grab the current live snapshot.

**Comment by tchellomello** [comment]
@chaddotson  correct that is the current behavior. We are working to get a way to capture the live streaming as you can see at #8

**Comment by tchellomello** [comment]
Closing this in reference to #8
