### ISSUE TITLE
Battery level

### ISSUE THREAD

**Issue by chaddotson** [tchellomello/python-arlo#20]
Any ideas on if battery level can be accessed via their API?  I've dug around watching the network requests but haven't seen anything.

**Comment by tchellomello** [comment]
@chaddotson  yes I want to add this to the library too so then we can extend Home Assistant sensors.  I'll research about it.

**Comment by chaddotson** [comment]
Battery level can be found in the subscribe event-stream endpoint.

**Comment by tchellomello** [comment]
@chaddotson  awesome let's try to implement it

**Comment by viswa-swami** [comment]
Battery level has been implemented as part of the current pull request in progress.  It would cover getting the mode as well as battery level.  There are properties added to also get the base station properties, camera properties,  rules etc.
