### ISSUE TITLE
Arm and Disarm

### ISSUE THREAD

**Issue by DkYSwe** [tchellomello/python-arlo#21]
Hi Guys,

Great work you have done!
Sorry for raising an issue but need your expertise since I couldn't find the documentation (saw an issue open for that).

Can you please assist me with info how I arm and disarm all cameras (at once)?

Im having a RPI integrated into my house alarm system which I want to trigger the arm/disarm of the Arlo system. 

Thanks in advance,

Daniel K

**Comment by viswa-swami** [comment]
In arlo, you have to arm/disarm in the base station and cannot perform action on individual cameras based on my usage/understanding.

arlo = PyArlo(<username>, <password>)
base = arlo.base_stations[0]   ====> Assuming you have only 1 base station (typical case)
base.mode = "armed"
To disarm: base.mode == "disarmed"

This has been integrated as part of Home Assistant and it is currently in Pull-Request stage.  It should probably be supported by Home Assistant once the review & tests are done.

**Comment by jwillaz** [comment]
If you have a SmartThings hub and set up the MQTT bridge for it, you can subscribe to a lot of Arlo camera topics.  https://github.com/stjohnjohnson/smartthings-mqtt-bridge  I currently use this method for interacting with my cameras, including turning them on/off individually.  I have Schlage Connect locks, so one of the nice automations I was able to do was trigger the front cameras to turn off when I unlock the door and also wait two minutes and turn the cameras on when I lock the door.  Works really well.

**Comment by tchellomello** [comment]
Closing it. Please refer to the new docs and commit #22 for further details
