### ISSUE TITLE
How to determine the current Arlo mode???

### ISSUE THREAD

**Issue by tchellomello** [tchellomello/python-arlo#5]
It seems to determine which is the current mode for the Arlo cameras, it is only possible if we consume the Angular.js object (I could not find a way to do it via request). 

So the library does have yet a way to determine which mode the cameras are set. 

We need to crack this out or how to implement it on our side. 

  - Should we just have a mode set after flipping it to the desired mode via pyarlo? 
  - How about the changes made on the webUI, how to update the state on PyArlo? 

Any ideas are very welcome.

**Comment by ryanwinter** [comment]
What are you referring to with the mode? 

Is this:
-  camera on/off; or
-  armed/disarmed/scheduled/geofenced/custom

**Comment by t9001** [comment]
I am also interested in this, I have not been able to figure out how to get the current base mode (armed/disarmed/scheduled/geofenced/custom). My solution would be to move all control to my libraries and store it myself. That would break if anyone changed things through the official app or website, but only until the API was used again. My coding skills are limited though, what do you mean by consuming the Angular.js object?

**Comment by viswa-swami** [comment]
**I have figured out how to get the mode.  I can help on this.  I am actually cloned the pyarlo and working on this feature.  I have a dirty code that is working, but working on finalizing it.**

**I will submit the PR in few days when it is done and tested.**

Basically our pyarlo code needs to subscribe with the base station for events.  Arlo will send event streams to pyarlo (basically us), when we request to get some information including mode, schedule, rules etc.

Once this event stream layer and subscription layer is complete, we can get the modes, rules, schedule etc.

**Comment by viswa-swami** [comment]
This event_Stream method is the method used by arlo.netgear.com (website) also.  Since we are getting the mode from the base station/device itself, it would sync up when we set via Home Assistant or even via arlo App/website.

**Comment by viswa-swami** [comment]
I am not sure if i can assign myself to this issue, but if you can, you may assign me this issue. (viswa.swami@gmail.com)

**Comment by tchellomello** [comment]
Implemented by PR #22
