### ISSUE TITLE
Arm/Disarm issue

### ISSUE THREAD

**Issue by jmrfsc** [tchellomello/python-arlo#58]
Hi,

when I'm trying to run the following example I'm getting the error bellow. Can you please help me? Regards.

%# connecting
from pyarlo import PyArlo
arlo  = PyArlo('xxx@xxx', 'xxxx')

%# get base station handle
%# assuming only 1 base station is available
base = arlo.base_stations[0]

%# get base mode
base.mode = 'disarmed'

Error running the command[Tecnologia][Arlo Netgear][Disarm] : Error on shell exec, return value : 1. Details : Array ( [0] => Traceback (most recent call last): File "/var/www/html/core/php/../../plugins/script/core/ressources/ArloDisarm.py", line 10, in base.mode = 'disarmed' File "/usr/local/lib/python2.7/dist-packages/pyarlo/base_station.py", line 374, in mode if mode not in self.available_modes: File "/usr/local/lib/python2.7/dist-packages/pyarlo/base_station.py", line 237, in available_modes return list(self.available_modes_with_ids.keys()) File "/usr/local/lib/python2.7/dist-packages/pyarlo/base_station.py", line 244, in available_modes_with_ids [(m.get("type", m.get("name")), m.get("id")) for m in modes] TypeError: 'NoneType' object is not iterable )

**Comment by chaddotson** [comment]
Was this resolved?  which version?  Seems it failed to return the list of valid modes when you set it.   I just tested with the master branch and it worked for me.
