### ISSUE TITLE
Arlo Q not supported

### ISSUE THREAD

**Issue by ryanwinter** [tchellomello/python-arlo#7]
I just bought a 2 pack of arlo q cameras. They are returning as devicetype == "arloq".

**Comment by tchellomello** [comment]
@ryanwinter  thanks for reporting this problem. 

On the code we are doing this:

https://github.com/tchellomello/python-arlo/blob/dev/pyarlo/__init__.py#L170-L175

```python
        for device in data.get('data'):
            name = device.get('deviceName')
            if ((device.get('deviceType') == 'camera' or
                 device.get('deviceType') == 'arloqs') and
                    device.get('state') == 'provisioned'):
                devices['cameras'].append(ArloCamera(name, device, self))
```

  Should it be `arloq` instead `arloqs`? 
  
  If so, please submit a patch with the change and I'll be happy to merge it.

**Comment by ryanwinter** [comment]
Mine is an "arloq", maybe "arloqs" is also a valid option because there is also the Arlo Q Plus which has local storage.

I will make a change and submit the patch. Might be a little slow as I'm still ramping up on git :D

**Comment by tchellomello** [comment]
@ryanwinter  sounds good.  Thank you!! :+1:

**Comment by ryanwinter** [comment]
#9
