### ISSUE TITLE
control camera shooting when Motion detection off

### ISSUE THREAD

**Issue by happenzZ** [tchellomello/python-arlo#89]
Can I control camera shooting by using python-arlo when I turn the motion detection off? I want to control the start time and end time for recording. If possible, use what functions?

**Comment by tchellomello** [comment]
Hello @happenzZ, 
   
   Unfortunately, that is not yet possible. All you can do is to enable the mode by arming or disarming and the camera will honor the configuration you have preset for the recording length. 

  Thank you for your question. 
mmello

**Comment by happenzZ** [comment]
Thanks for your reply.

Actually, I want the camera to record longer videos. Since in the arming mode, it seems that the maximum record time for one camera is 300 sec (Record until activity stops) and 120 sec (Record for a fixed length of time).

**So, in your opinion, currently, there is no way to record longer videos? Am I get your point correctly?**

BTW, if control the camera manually from the interface provided in the website (click the button highlighted in the photo), if seems that I can control the start time and end time of recording. So I can record longer videos.  So I wonder if it is possible to control this button using python-arlo.
![image](https://user-images.githubusercontent.com/8804573/42144115-f5bc1094-7deb-11e8-8273-fcda0e46c5b6.png)


Best,
Haipeng
