### ISSUE TITLE
Arlo Baby 'get' Commands?

### ISSUE THREAD

**Issue by schmittx** [tchellomello/python-arlo#93]
Is there a current method to 'get' the following status on the Arlo Baby? I see that there's commands to change the status but I'm not sure how to get the current status.
- volume level
- night light on/off
- night light brightness

**Comment by lukiffer** [comment]
I don't recall seeing these when I was poking around their API, but then again I wasn't actively looking for them. I'll take a peek and see if I can locate them in the API.

**Comment by lukiffer** [comment]
It looks like another async request is being made to `cameras/{deviceId}` with the response coming back over the subscription channel. 

Volume comes through as:
```
      "speaker": {
        "mute": false,
        "volume": 100
      },
```

Nightlight data comes through as:
```
      "nightLight": {
        "brightness": 200,
        "enabled": false,
        "mode": "temperature",
        "sleepTime": 0,
        "sleepTimeRel": 0,
        "temperature": 2650
      },
```

I'll try to get these patched into the base station code soon, but my availability has been all over the place due to the viewing target of my Arlo Baby :)

**Comment by schmittx** [comment]
Nice work, I understand the availability concern...no problem.

**Comment by lukiffer** [comment]
Just submitted a **wip** PR for the features requested. I'm guessing it will fail coveralls as there are code paths that aren't covered by my first pass of tests, but I've tested it and it's working with my Arlo Baby.

@schmittx I'd be interested in your feedback whether you'd prefer us get this tested and released with just the features you requested, or should we work on exposing more of the data that comes back in this request? Take a look at the [fixture](https://github.com/lukiffer/python-arlo/blob/feature/baby_extended_properties/tests/fixtures/pyarlo_extended_properties.json) and see if there's anything else in here you're interested in.

Should be able to finish up the missing tests this weekend.

**Comment by schmittx** [comment]
Nice work!

Personally speaking, the only other data point worth looking at would be the night light color/temperature (which I think are “mode” and “temperature” within “nightLight”). A ‘get’ and ‘set’ would be ideal for color and/or temperature.
